/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DeleteAccess: typeof import('./src/components/base/deleteAccess.vue')['default']
    Search: typeof import('./src/components/base/search.vue')['default']
  }
}
